const $=(id)=>document.getElementById(id);
let stream=null,track=null,audioCtx=null,analyser=null,prev=null,running=false,lastFrame=null,lastDims={w:520,h:292};
let sensitivity='balanced',hunterMode=false,showAll=true,manualArmed=false,zoomLevel=1,nextTrackId=1,contrastBoost=true;
let audioScore=0,motionScore=0,wallScore=0,lockScore=0,avgLum=0,tracks=[];
let profile=loadProfile(),samples=loadSamples();

function bind(){
['startBtn','academyStartBtn','profileStartBtn','menuBtn','closeMenuBtn','openAcademyBtn','closeAcademyBtn','openProfileBtn','closeProfileBtn','saveProfileBtn','stopBtn','manualBtn','toggleHunterBtn','zoomBtn','cycleModeBtn','contrastBtn','showAllBtn','confirmMosquito','rejectTarget','catchShotBtn','exportDataBtn'].forEach(id=>{ if(!$(id)) console.warn('missing',id); });
$('startBtn').onclick=startHunt;$('academyStartBtn').onclick=openAcademy;$('profileStartBtn').onclick=openProfile;
$('menuBtn').onclick=()=>$('menuSheet').classList.remove('hidden');$('closeMenuBtn').onclick=()=>$('menuSheet').classList.add('hidden');
$('openAcademyBtn').onclick=openAcademy;$('closeAcademyBtn').onclick=closeAcademy;$('openProfileBtn').onclick=openProfile;$('closeProfileBtn').onclick=closeProfile;$('saveProfileBtn').onclick=saveProfile;
$('stopBtn').onclick=stopHunt;$('manualBtn').onclick=armManual;$('toggleHunterBtn').onclick=toggleHunter;$('zoomBtn').onclick=cycleZoom;$('cycleModeBtn').onclick=cycleSensitivity;$('contrastBtn').onclick=toggleContrast;$('showAllBtn').onclick=toggleShowAll;
$('confirmMosquito').onclick=()=>labelBest(true);$('rejectTarget').onclick=()=>labelBest(false);$('catchShotBtn').onclick=makeCatchShot;$('exportDataBtn').onclick=exportSamples;$('overlay').addEventListener('pointerdown',manualTarget);
}
function loadProfile(){return JSON.parse(localStorage.getItem('mh_profile_v09')||'{"name":"Guest Hunter","kills":0,"xp":0,"shots":0}')}
function loadSamples(){return JSON.parse(localStorage.getItem('mh_samples_v09')||'[]')}
function saveSamples(){localStorage.setItem('mh_samples_v09',JSON.stringify(samples.slice(-300)))}
function saveProfileData(){localStorage.setItem('mh_profile_v09',JSON.stringify(profile))}
function rankForXP(xp){if(xp>=5000)return['Mosquito Overlord',6,'👑🦟'];if(xp>=2500)return['Night Stalker',5,'🥷🦟'];if(xp>=1200)return['Swarm Slayer',4,'🛡️🦟'];if(xp>=500)return['Hunter Elite',3,'🎯🦟'];if(xp>=150)return['Hunter',2,'🧢🦟'];return['Rookie',1,'🧢']}
function refreshProfileUI(){const [rank,level,avatar]=rankForXP(profile.xp);$('hunterNameOut').textContent=profile.name;$('xpOut').textContent=profile.xp;$('killOut').textContent=profile.kills;$('profileRank').textContent=rank;$('profileLevel').textContent=level;$('profileKills').textContent=profile.kills;$('profileXP').textContent=profile.xp;$('avatar').textContent=avatar;$('hunterNameInput').value=profile.name;$('xpBar').style.width=Math.min(100,profile.xp/50)+'%';$('nextRankText').textContent='Keep hunting to unlock gear.';$('gearText').textContent=['Rookie cap unlocked.','Hunter cap + tracker.','Elite goggles unlocked.','Swarm shield unlocked.','Night cloak unlocked.','Golden crown unlocked.'][level-1]}

async function startHunt(){try{$('startScreen').classList.add('hidden');$('academyScreen').classList.add('hidden');$('profileScreen').classList.add('hidden');$('huntScreen').classList.remove('hidden');refreshProfileUI();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30}},audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});const v=$('video');v.srcObject=stream;await v.play();track=stream.getVideoTracks()[0];setupAudio(stream);running=true;requestAnimationFrame(scanFrame);setInterval(updateHud,250)}catch(e){alert('Starten lukt niet: '+e.message);$('huntScreen').classList.add('hidden');$('startScreen').classList.remove('hidden')}}
function setupAudio(s){audioCtx=new(window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(s);analyser=audioCtx.createAnalyser();analyser.fftSize=4096;src.connect(analyser)}
function scanAudio(){if(!analyser||!audioCtx)return;const data=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(data);let peak=0,idx=0;for(let i=0;i<data.length;i++){if(data[i]>peak){peak=data[i];idx=i}}const freq=idx*audioCtx.sampleRate/analyser.fftSize;let s=0;if(freq>=380&&freq<=850)s+=44;if(freq>=430&&freq<=700)s+=16;if(peak>55)s+=Math.min(40,(peak-55)*1.05);audioScore=Math.round(clamp(s,0,100))}
function scanFrame(){if(!running)return;const v=$('video'),ov=$('overlay'),o=ov.getContext('2d');ov.width=v.clientWidth;ov.height=v.clientHeight;o.clearRect(0,0,ov.width,ov.height);const w=520,h=Math.max(292,Math.round(w*(v.videoHeight||1080)/(v.videoWidth||1920)));lastDims={w,h};const c=$('workCanvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});if(v.videoWidth>0){$('testCamera').textContent='OK';const vw=v.videoWidth,vh=v.videoHeight,cw=vw/zoomLevel,ch=vh/zoomLevel;ctx.drawImage(v,(vw-cw)/2,(vh-ch)/2,cw,ch,0,0,w,h);let frame=ctx.getImageData(0,0,w,h);if(contrastBoost)frame=enhanceFrame(frame);lastFrame=frame;avgLum=avg(frame);$('lightOut').textContent=Math.round(avgLum);const det=[...scanMotion(frame,w,h),...scanWall(frame,w,h)];updateTracks(det,w,h);drawTracks(o,ov,w,h);prev=frame}scanAudio();const top=tracks[0],best=top?top.score:0;if(top&&(top.manual||(best>=82&&top.hits>=2)))lockScore=Math.min(100,lockScore+5);else lockScore=Math.max(0,lockScore-1.5);requestAnimationFrame(scanFrame)}
function enhanceFrame(f){const d=f.data;for(let i=0;i<d.length;i+=4){d[i]=clamp((d[i]-128)*1.18+128,0,255);d[i+1]=clamp((d[i+1]-128)*1.18+128,0,255);d[i+2]=clamp((d[i+2]-128)*1.18+128,0,255)}return f}
function avg(f){const d=f.data;let t=0,n=0;for(let i=0;i<d.length;i+=100){t+=lum(d,i);n++}return t/n}
function scanMotion(f,w,h){if(!prev){motionScore=0;return[]}const step=4,threshold=sensitivity==='dark'?82:avgLum<70?92:72;let total=0,sx=0,sy=0,minX=w,maxX=0,minY=h,maxY=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4,d=Math.abs(f.data[i]-prev.data[i])+Math.abs(f.data[i+1]-prev.data[i+1])+Math.abs(f.data[i+2]-prev.data[i+2]);if(d>threshold){total++;sx+=x;sy+=y;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}$('motionPxOut').textContent=total;$('testMotion').textContent=total>0?'active':'idle';const area=Math.max(1,(maxX-minX)*(maxY-minY));if(total>=2&&total<(sensitivity==='strict'?160:260)&&area<9000){const score=clamp(45+total*.25+clamp((total*18)/area,0,1)*28+(audioScore>45?8:0),0,99);motionScore=Math.round(score);return[{x:sx/total,y:sy/total,type:'motion',score:motionScore}]}motionScore=Math.max(0,motionScore-6);return[]}
function scanWall(f,w,h){const step=sensitivity==='dark'?3:4,d=f.data,cand=[],isDark=avgLum<76,contrastMin=sensitivity==='strict'?58:sensitivity==='dark'?42:50,bgMin=isDark?38:80,lumMax=isDark?118:125,textureMax=sensitivity==='strict'?32:sensitivity==='dark'?48:40;for(let y=14;y<h-14;y+=step)for(let x=14;x<w-14;x+=step){const i=(y*w+x)*4,center=lum(d,i);let ring=0,n=0,variance=0,s=[];for(let dy=-12;dy<=12;dy+=12)for(let dx=-12;dx<=12;dx+=12){if(dx===0&&dy===0)continue;const l=lum(d,((y+dy)*w+(x+dx))*4);s.push(l);ring+=l;n++}const bg=ring/n;for(const q of s)variance+=Math.abs(q-bg);variance/=s.length;const contrast=bg-center;if(contrast>contrastMin&&bg>bgMin&&center<lumMax&&variance<textureMax)cand.push({x,y,contrast,texture:variance})}$('wallDotsOut').textContent=cand.length;$('testWall').textContent=cand.length>0?'active':'idle';const clusters=[];for(const p of cand){let hit=false;for(const c of clusters){const dx=c.x-p.x,dy=c.y-p.y;if(dx*dx+dy*dy<130){c.x=(c.x*c.n+p.x)/(c.n+1);c.y=(c.y*c.n+p.y)/(c.n+1);c.contrast=Math.max(c.contrast,p.contrast);c.texture=(c.texture*c.n+p.texture)/(c.n+1);c.n++;hit=true;break}}if(!hit)clusters.push({x:p.x,y:p.y,contrast:p.contrast,texture:p.texture,n:1})}const filtered=clusters.filter(c=>c.n>=1&&c.n<=12).map(c=>({x:c.x,y:c.y,type:'wall',score:Math.round(clamp(52+(c.n>=2&&c.n<=6?22:8)+clamp((c.contrast-contrastMin)*1.8,0,34)+(sensitivity==='dark'?12:0)+(audioScore>45?8:0)-c.texture*.45,0,99))})).filter(c=>c.score>=70).sort((a,b)=>b.score-a.score).slice(0,4);wallScore=filtered.length?filtered[0].score:Math.max(0,wallScore-5);return filtered}
function updateTracks(det,w,h){for(const t of tracks){t.age++;t.ttl--;t.score=Math.max(0,t.score-(t.manual?.08:.55))}for(const d of det){let best=null,bd=99999;for(const t of tracks){const dx=t.x-d.x,dy=t.y-d.y,dist=dx*dx+dy*dy,gate=t.manual?4200:d.type==='motion'?2200:1400;if(dist<bd&&dist<gate){best=t;bd=dist}}if(best){best.x=best.x*.72+d.x*.28;best.y=best.y*.72+d.y*.28;if(!best.manual)best.type=d.type;best.hits++;best.ttl=best.manual?480:d.type==='motion'?180:240;best.score=clamp(best.score*.62+d.score*.38+Math.min(16,best.hits*1.2),0,100)}else tracks.push({id:nextTrackId++,x:d.x,y:d.y,type:d.type,score:d.score,hits:1,age:0,ttl:d.type==='motion'?150:210,manual:false})}tracks=tracks.filter(t=>t.ttl>0&&t.score>25).sort((a,b)=>b.score-a.score).slice(0,8);$('tracksOut').textContent=tracks.length}
function drawTracks(ctx,ov,w,h){const top=tracks[0];for(const t of tracks){const threshold=hunterMode?85:showAll?30:60;if(!t.manual&&t.score<threshold)continue;if(hunterMode&&t!==top&&!t.manual)continue;const x=t.x*ov.width/w,y=t.y*ov.height/h,conf=Math.round(t.score);drawTarget(ctx,x,y,t.manual?58:t.type==='motion'?48:36,t.manual?'#2b8cff':t.type==='motion'?'#ff2828':'#00ff78',`${conf}% ${t.manual?'MANUAL':t.type==='motion'?'MOVING':'STILL'}`)}}
function drawTarget(ctx,x,y,r,color,label){ctx.strokeStyle=color;ctx.lineWidth=5;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle=color;ctx.font='bold 16px Arial';ctx.fillText(label,x+r+7,y-5)}
function updateHud(){const best=tracks.length?tracks[0].score:0;$('confidenceOut').textContent=Math.round(best)+'%';$('motionThreat').textContent='Motion: '+label(motionScore);$('wallThreat').textContent='Wall: '+label(wallScore);$('samplesOut').textContent=samples.length;$('testSamples').textContent=samples.length;refreshProfileUI();$('scanAssist').textContent=avgLum<25?'Too dark':motionScore>55?'Motion active':wallScore>70?'Wall candidate':best>80?'Strong target':'Scan slowly';if(lockScore>70&&tracks.length){const top=tracks[0];$('lockState').textContent=top.manual?'🔵 MANUAL LOCK':top.type==='motion'?'🔴 MOTION LOCK':'🟢 WALL LOCK';$('lockState').style.background=top.manual?'rgba(43,140,255,.92)':top.type==='motion'?'rgba(229,9,20,.92)':'rgba(0,160,80,.92)'}else{$('lockState').textContent=best>=80?'High confidence':'Scanning';$('lockState').style.background='rgba(0,0,0,.75)'}}
function armManual(){manualArmed=true;$('manualToast').classList.remove('hidden');$('manualState').textContent='Manual: armed';$('testManual').textContent='armed';setTimeout(()=>{if(manualArmed){manualArmed=false;$('manualToast').classList.add('hidden');$('manualState').textContent='Manual: off';$('testManual').textContent='ready'}},8000)}
function manualTarget(ev){if(!manualArmed)return;ev.preventDefault();const ov=$('overlay'),r=ov.getBoundingClientRect(),x=(ev.clientX-r.left)/ov.width*lastDims.w,y=(ev.clientY-r.top)/ov.height*lastDims.h;tracks.unshift({id:nextTrackId++,x,y,type:'manual',score:96,hits:10,age:0,ttl:520,manual:true});tracks=tracks.slice(0,8);lockScore=100;manualArmed=false;$('manualToast').classList.add('hidden');$('manualState').textContent='Manual: locked';$('testManual').textContent='locked';captureSample(x,y,'manual_candidate');if(navigator.vibrate)navigator.vibrate([50,25,50])}
function captureSample(x,y,label){if(!lastFrame)return;const w=lastDims.w,h=lastDims.h,src=document.createElement('canvas'),sctx=src.getContext('2d');src.width=w;src.height=h;sctx.putImageData(lastFrame,0,0);const size=90,crop=document.createElement('canvas'),cctx=crop.getContext('2d');crop.width=140;crop.height=140;cctx.drawImage(src,Math.max(0,x-size/2),Math.max(0,y-size/2),size,size,0,0,140,140);samples.push({ts:Date.now(),label,score:tracks[0]?Math.round(tracks[0].score):0,zoom:zoomLevel,mode:sensitivity,light:Math.round(avgLum),image:crop.toDataURL('image/jpeg',0.72)});saveSamples()}
function labelBest(isMug){if(!tracks.length){alert('Geen target. Gebruik Manual of scan opnieuw.');return}captureSample(tracks[0].x,tracks[0].y,isMug?'confirmed_mosquito':'rejected');if(isMug){profile.kills++;profile.xp+=50+(tracks[0].manual?10:25);saveProfileData();tracks[0].score=100;tracks[0].ttl=520;lockScore=100}else{tracks.shift();lockScore=Math.max(0,lockScore-30)}refreshProfileUI()}
function exportSamples(){if(!samples.length){alert('Nog geen samples.');return}const blob=new Blob([JSON.stringify(samples,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mosquito-hunter-samples-v09.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function makeCatchShot(){const canvas=$('shareCanvas'),ctx=canvas.getContext('2d'),v=$('video'),top=tracks[0],rank=rankForXP(profile.xp);ctx.fillStyle='#070707';ctx.fillRect(0,0,1080,1920);try{ctx.drawImage(v,0,0,1080,1450)}catch(e){}ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(0,1320,1080,600);ctx.fillStyle='#00ff78';ctx.font='bold 60px Arial';ctx.fillText('MOSQUITO HUNTER',60,1410);ctx.fillStyle='#fff';ctx.font='bold 48px Arial';ctx.fillText(profile.name,60,1485);ctx.fillStyle='#ffcf33';ctx.font='bold 44px Arial';ctx.fillText(rank[0]+'  '+rank[2],60,1555);ctx.fillStyle='#fff';ctx.font='38px Arial';ctx.fillText('Kills: '+profile.kills+'   XP: '+profile.xp,60,1630);ctx.fillText('Target confidence: '+(top?Math.round(top.score):0)+'%',60,1690);ctx.fillText(new Date().toLocaleString(),60,1750);canvas.toBlob(blob=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mosquito-hunter-catch.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})}
function saveProfile(){profile.name=$('hunterNameInput').value.trim()||'Guest Hunter';saveProfileData();refreshProfileUI();alert('Profile saved.')}
function openProfile(){$('menuSheet').classList.add('hidden');refreshProfileUI();$('startScreen').classList.add('hidden');$('huntScreen').classList.add('hidden');$('academyScreen').classList.add('hidden');$('profileScreen').classList.remove('hidden')}
function closeProfile(){$('profileScreen').classList.add('hidden');running?$('huntScreen').classList.remove('hidden'):$('startScreen').classList.remove('hidden')}
function openAcademy(){$('menuSheet').classList.add('hidden');$('startScreen').classList.add('hidden');$('huntScreen').classList.add('hidden');$('profileScreen').classList.add('hidden');$('academyScreen').classList.remove('hidden')}
function closeAcademy(){$('academyScreen').classList.add('hidden');running?$('huntScreen').classList.remove('hidden'):$('startScreen').classList.remove('hidden')}
function toggleHunter(){hunterMode=!hunterMode;$('toggleHunterBtn').textContent='Hunter Mode: '+(hunterMode?'ON':'OFF')}
function toggleShowAll(){showAll=!showAll;$('showAllBtn').textContent='Show: '+(showAll?'All targets':'Strong only')}
function cycleSensitivity(){sensitivity=sensitivity==='balanced'?'strict':sensitivity==='strict'?'dark':'balanced';$('cycleModeBtn').textContent='Detection: '+(sensitivity==='dark'?'Dark':sensitivity==='strict'?'Strict':'Balanced')}
function toggleContrast(){contrastBoost=!contrastBoost;$('contrastBtn').textContent='Contrast: '+(contrastBoost?'ON':'OFF')}
async function cycleZoom(){zoomLevel=zoomLevel===1?2:zoomLevel===2?3:1;$('zoomBtn').textContent=`Zoom: ${zoomLevel}x`;if(track&&track.getCapabilities){const caps=track.getCapabilities();if(caps.zoom){try{await track.applyConstraints({advanced:[{zoom:Math.min(caps.zoom.max,Math.max(caps.zoom.min,zoomLevel))}]})}catch(e){}}}}
function stopHunt(){running=false;$('menuSheet').classList.add('hidden');if(stream)stream.getTracks().forEach(t=>t.stop());if(audioCtx)audioCtx.close();stream=null;track=null;prev=null;tracks=[];$('huntScreen').classList.add('hidden');$('startScreen').classList.remove('hidden')}
function lum(d,i){return .2126*d[i]+.7152*d[i+1]+.0722*d[i+2]}function clamp(v,min,max){return Math.max(min,Math.min(max,v))}function label(v){return v>70?'HIGH':v>35?'MEDIUM':'LOW'}
bind();refreshProfileUI();
